# COLOQUE O NOME DO SEU BOT AQUI (tem que ser único, tudo junto)
app = "dnzx-lacasamods"

# REGIÃO MAIS PERTO DO BRASIL: gig = Rio de Janeiro, melhor conexão
primary_region = "gig"

[build]
# vai usar o Dockerfile que você já criou, não muda nada aqui

[env]
# nada aqui, token fica seguro nos secrets

[services]
  internal_port = 8080
  protocol = "tcp"

[deploy]
  auto_stop_machines = false # IMPORTANTE: NÃO DESLIGA O BOT
  auto_start_machines = true
  min_machines_running = 1 # sempre ligado 24h
  
